#!/bin/csh -f

set N = 1                                       #run tag
set runDir = /shared/users/asousa/WIPP/WIPPcodeLEP                 #current directory
set rayMaker = makeMultipleNewrayInC_smoothLK6  #rayMaker to execute
set readOne = readOneA                          #readOne to execute
set calc = calcFluxA                            #calcFlux to execute

#set important variables that will be used in all parts

set bot = 0         # Frequency limit indices for ray maker
set top = 31        # (129 bins: 130 does all)
set makeRays = 1
set runProg = 1
set runFlux = 0
set centerLats = ( 25 35 45 55 )

foreach centerLat ( $centerLats )
    echo ----- Starting at centerLat = $centerLat -----
   # set centerLat = 35

    set outDir = $runDir/outshort_$centerLat
    # L-shells to calculate scattering along:

    # # Call makeFreqFiles
    echo ---calling makeFreqFiles---
        ./makeFreqFiles_par.sh $centerLat $rayMaker $readOne $outDir $bot $top \
        $makeRays $runProg ${centerLat}deg


    cp -f $runDir/runfiles/$calc .


    set L_TARG=( 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 2.1 2.2 \
                 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.0 3.1 3.2 \
                 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.0 4.1 4.2 \
                 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.0 5.1 5.2 )
    # set L_TARG=(2.2)

    # call calcFlux
    if ($runFlux == 1) then
     echo ---calling calcFlux---
     # Clear existing alpha and phi files
     rm -r $outDir/alpha*
     rm -r $outDir/phi*

     foreach L ( $L_TARG )
        echo Running for L = $L
     #   #qsub -j oe -o log.txt -l nodes=1:ppn=1 -l walltime=24:00:00 ./$calc $outDir $L
        ./$calc $outDir $L
     end
    endif
end
# qstat
#exit 0
