#!/bin/csh -f
# Remove all old files and compile all components of the wipp-code.
# This is more a reference for how to compile what as opposed to a useful
# script that you should actually run frequently.
# Kevin Graf - 090612

# rm -f runfiles/calcFluxB \
#       runfiles/damping \
#       runfiles/makeMultipleNewrayInC_smoothLK6 \
#       runfiles/readOneFileInC \
#       runfiles/newray

# gcc -o runfiles/calcFluxB codesrc/calcFlux_bob.c -lm
# gcc -o runfiles/calcFlux codesrc/calcFlux.c -lm
# gcc -o runfiles/damping codesrc/damping.c -lm
# gcc -o runfiles/makeMultipleNewrayInC_smoothLK6 codesrc/makeMultipleNewrayInC_smoothLK6.c -lm
# gcc -o runfiles/readOneFileInC codesrc/readOneFileInC_102903.c -lm

# gfortran -fno-automatic -o runfiles/newray codesrc/newray1.8.f

# Austin's versions:
gcc -o runfiles/calcFluxA codesrc/calcFlux_austin.c -lm
gcc -o runfiles/readOneA codesrc/readOneFileInC_austin.c -lm

